### ISSUE TITLE
find_and_modify bypasses validations

### ISSUE THREAD

**Issue by juliancooper** [mongoid/mongoid#3784]
I'm not sure if this is intended or unavoidable behaviour, but using find_and_modify allows setting a document's fields to invalid values.

Example:
The following works:
```ruby
job = Job.where(status: :pending).asc(:time_created).find_and_modify({"$set" => {status: :processing}}, new: true)
```
Despite the validation in the model below.
```ruby
# models/job.rb
# ...
field :status, type: Symbol, default: :pending
# ...
validates_inclusion_of :status, in: [:pending, :active, :completed, :failed]
```

**Comment by durran** [comment]
Yes this is intended behaviour as no documents are actually loaded into memory when executing the `find_and_modify` of the criteria API - therefore we have no way of running validation. This is because we are using the underlying database command `$findAndModify` which does all modifications before returning the document.
