### ISSUE TITLE
Default primary_key

### ISSUE THREAD

**Issue by gauthier-delacroix** [mongoid/mongoid#3793]
I'm using `primary_key` in many relations because I don't want to expose MongoDB `_id` on my API (maybe there's a better way with serializers but I find convenient that API and DB associations use the same field).

Is there a way to define the default primary key of a model, since there's chance this model will always be associated through the same field ?

If not, I could try to PR this feature but I'm not sure how you would implement it.

My idea is quite simple : Strore the default primary key in the document so that each relation can look for this data to store it in its metadata instead of directly `_id`.

Here's an example:
````ruby
class User
  include Mongoid::Document
  field :_api_id, type: String, default: ->{SecureRandom.urlsafe_base64(10)}
  field :first_name, type: String
  field :surname, type: String
  primary_key :_api_id
  has_many :posts # No need to add `primary_key: :_api_id` here
  has_many :comments # Neither here
  [...]
end

class Post
  include Mongoid::Document
  field :Text, type: String
  belongs_to: :user # Neither here
  [...]
end
````
My question about how to implement it is: where should I store the default primary key option ? Directly in a `class_attribute` in `Mongoid::Document` ? In `Mongoid::Relations` ?

Thanks !

**Comment by durran** [comment]
No this is not possible since all documents in MongoDB require an `_id` field, unlike relational databases, and is always treated on the database side as the primary key, and is always indexed. Therefore it's not really a feature we would want to have in the core lib. My suggestion would be to so as you stated and use serializers for the API representations.
