### ISSUE TITLE
embed without an _id

### ISSUE THREAD

**Issue by mphstudios** [mongoid/mongoid#3794]
Versions 2.1.8 removed the `embedded_object_id` configuration parameter, issue #740, however that was a global configuration. Is there any documentation on how to embed a document which does not have an `_id` on a per model basis?

**Comment by durran** [comment]
Mongoid requires the ids to be on the embedded documents in order for it's relationships to function properly, as well as atomic updates since the $ positional operator in MongoDB is not fully-functional. Therefor we do not provide a way to do this out of the box and cannot make any guarantees of everything working properly if the ids are removed.
