### ISSUE TITLE
When a hash attribute's field is updated via [], changed? returns false

### ISSUE THREAD

**Issue by myrridin** [mongoid/mongoid#4029]
When a document has a hash field, accessing it via [] and updating a property does not cause changed? to return true. I've been able to reproduce this error, but unable to discover a solution so far.

To reproduce, place these tests in changeable_spec.rb

The first one should pass, and the second should fail reproducing the error described above.
```
context "when a subfield is changed" do

  let(:person) do
    Person.create(map: { name: "value" })
  end

  it "returns true" do
    person.map[:name] = "Another Person"
    expect(person).to be_changed
  end

  it "returns true if accessed via []" do
    person[:map][:name] = "The Third Person"
    expect(person).to be_changed
  end
end
```

**Comment by durran** [comment]
This is because `[]` access is aliased to `read_attribute` which doesn't have any sort of dirty tracking around it like the named getter has. If you want proper dirty tracking you will always need to use the getter, since it wraps `read_attribute` and alerts that the value can change. This functions as designed.
