### ISSUE TITLE
 === operator not working as expected on Mongoid::Relations::Many

### ISSUE THREAD

**Issue by knovoselic** [mongoid/mongoid#4077]
Let's say we have `User` model with `has_many :devices` relation.

If `val` is set to `user.devices`, consider the following:

    [14] pry(#<RSpec::Matchers::BuiltIn::ChangeDetails>)> val.is_a? Enumerable
    => true
    [15] pry(#<RSpec::Matchers::BuiltIn::ChangeDetails>)> val.is_a? Array
    => true

So far everything is good. But shouldn't the following tests also return true?

    [16] pry(#<RSpec::Matchers::BuiltIn::ChangeDetails>)> Array === val
    => false
    [17] pry(#<RSpec::Matchers::BuiltIn::ChangeDetails>)> Enumerable === val
    => false

You can find full repro here (all tests should pass):
https://github.com/knovoselic/rspec-expectations-change-bug-repro

I thought this was an rspec-expectations issue, but it turns out it's Mongoid issue. Please see this for more details:
https://github.com/rspec/rspec-expectations/issues/791

**Comment by myronmarston** [comment]
To clarify what @knovoselic said:

* Making `Array === val` return `true` requires `val` to actually _be_ an array or requires `Array.===` to be monkey-patched.  That's going to be problematic as long as Mongoid implements its relations as proxies.  If Mongoid relations are intended to be "array-like" but not actually be an array, I would not expect `Array === val` to return true, anyway.
* RSpec relies upon `Enumerable === val` to see if an item is a collection.  We use `SomeModule === val` over `val.is_a?(SomeModule)` throughout RSpec because we deal with all manner of user objects and we can't generally trust that `is_a?` will work properly -- for example, the user may have defined `is_a?` in domain terms for their app (e.g. `player.is_a?(:goalie)` or whatever), so we can't trust it like we can trust `Module#===`.
* RSpec's `change` master dups collections in order to see if they changed -- otherwise it simply has two identical references to the same collection and it (naturally) sees it as having not changed.
* So, for a collection object to work properly with RSpec's `change` matcher, it needs to `include Enumerable` so RSpec sees it as being a collection.
* Of course, including `Enumerable` brings with it additional capabilities of its own, and would probably be useful in its own right.

All that's to say that if `Mongoid::Relations::Many` included `Enumerable`, @knovoselic's case would work properly in RSpec.  The `Array === val` issue can be confusing for users but doesn't seem to have a clear solution (given that you use proxies) and doesn't affect RSpec.

I noticed you put this in the 5.0.0 milestone, @durran.  Hopefully `Enumerable` could be included before then since it's such a minor change?
