### ISSUE TITLE
Rspec Error: spec_helper.rb:78:in `non_legacy_server?': undefined method `features' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by jstrocel** [mongoid/mongoid#4105]
When I try and run the test suite, I get this error:

l/work/rails/mongoid/spec/spec_helper.rb:78:in `non_legacy_server?': undefined method `features' for nil:NilClass (NoMethodError)

Is there an extra setup step that I'm missing?

**Comment by estolfo** [comment]
You'll get that message if you can't connect to a mongod. Is your mongod running? If it's not on the default host and port (localhost:27017) then set the MONGODB_ADDRESSES environment variable.

See the line here:
https://github.com/mongodb/mongo-ruby-driver/blob/master/spec/support/authorization.rb#L28-L29

**Comment by durran** [comment]
That's going to happen either in the case above, or if mongod is running and the following cases are true:

- Auth is disabled. You will then need to be running mongo with authentication enabled.
- Auth is enabled and you are not starting with a clean server. Mongoid adds a root user to the server before running the specs in order to add it's own users for authentication in the test suite.

To help see which one, you can `raise e` in `spec_helper` if you want to see if auth is your case:

https://github.com/mongoid/mongoid/blob/master/spec/spec_helper.rb#L120
