### ISSUE TITLE
Port usage through the roof / IOError / 5.0.0.beta

### ISSUE THREAD

**Issue by lucasmartins** [mongoid/mongoid#4128]
I'm not sure if this is a MongoDB, Mongoid or Moped problem, but I'm getting massive port usage while inserting into the database.

It looks like that for each insert the driver is opening a new connection to the database, spawning a never dying thread which keeps it's own port open.

The log near the error:
```
# ... this goes for a while ...
D, [2015-07-14T15:35:13.714276 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.insert | SUCCEEDED | 0.004395s
D, [2015-07-14T15:35:13.716073 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.find | STARTED | {:filter=>{"_id"=><BSON::ObjectId:0x70241950927080 data=55a556595175610ba6000420>}, :project=>nil, :skip=>nil, :limit=>nil, :flags=>[:slave_ok]}
D, [2015-07-14T15:35:13.716664 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.find | SUCCEEDED | 0.00062s
D, [2015-07-14T15:35:13.717464 #2982] DEBUG -- : MONGODB | Adding 127.0.0.1:27017 to the cluster. | runtime: 0.0079ms
D, [2015-07-14T15:35:13.725873 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.insert | STARTED | {:insert=>"invoice_lines_calls", :documents=>[{"_id"=><BSON::ObjectId:0x70241894454620 data=55a556615175610ba600057b>, "caller"=>"REDACTED", "timestamp"=>2014-12-05 14:20:18 UTC, "duration"=>66, "destination_prefix"=>"48", "destination_number"=>"9...
D, [2015-07-14T15:35:13.731809 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.insert | SUCCEEDED | 0.006016s
D, [2015-07-14T15:35:13.733481 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.find | STARTED | {:filter=>{"_id"=><BSON::ObjectId:0x70241950927080 data=55a556595175610ba6000420>}, :project=>nil, :skip=>nil, :limit=>nil, :flags=>[:slave_ok]}
D, [2015-07-14T15:35:13.733899 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.find | SUCCEEDED | 0.000453s
D, [2015-07-14T15:35:13.734600 #2982] DEBUG -- : MONGODB | Adding 127.0.0.1:27017 to the cluster. | runtime: 0.0069ms
D, [2015-07-14T15:35:13.749801 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.insert | STARTED | {:insert=>"invoice_lines_calls", :documents=>[{"_id"=><BSON::ObjectId:0x70241898694400 data=55a556615175610ba600057c>, "caller"=>"REDACTED", "timestamp"=>2014-12-05 17:36:11 UTC, "duration"=>30, "destination_prefix"=>"48", "destination_number"=>"9...
D, [2015-07-14T15:35:13.754060 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.insert | SUCCEEDED | 0.004342s
D, [2015-07-14T15:35:13.756130 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.find | STARTED | {:filter=>{"_id"=><BSON::ObjectId:0x70241950927080 data=55a556595175610ba6000420>}, :project=>nil, :skip=>nil, :limit=>nil, :flags=>[:slave_ok]}
D, [2015-07-14T15:35:13.756601 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.find | SUCCEEDED | 0.000509s
D, [2015-07-14T15:35:13.757380 #2982] DEBUG -- : MONGODB | Adding 127.0.0.1:27017 to the cluster. | runtime: 0.0079ms
D, [2015-07-14T15:35:13.764873 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.insert | STARTED | {:insert=>"invoice_lines_calls", :documents=>[{"_id"=><BSON::ObjectId:0x70241898792900 data=55a556615175610ba600057d>, "caller"=>"REDACTED", "timestamp"=>2014-12-06 15:15:23 UTC, "duration"=>30, "destination_prefix"=>"48", "destination_number"=>"9...
D, [2015-07-14T15:35:13.769091 #2982] DEBUG -- : MONGODB | 127.0.0.1:27017 | mx_test.insert | FAILED | IOError | 0.004289s
``` 
As reported by the activity monitor just before the app crashed:
- mongod Threads: 1716;
- mongod Ports: 1701; 

I find it weird that for each insert there's a `Adding 127.0.0.1:27017 to the cluster` entry.

There are 1022 inserts on the `invoice_lines_calls` collection before the crash.

This app is running normally at dev/test/staging/production on MongoDB 2.6 + Mongoid 4.

This test is part of the rspec suite, and it was run locally on OSX using (single instance) MongoDB 3.0.4  + Mongoid 5.0.0.beta . All these inserts are running from the same Sidekiq process/job.

Any ideas on how to narrow down the problem? I'm willing dig this up to the bone.

**Comment by durran** [comment]
Can you show some sample code, maybe the sidekiq worker code? I can give you some background on where to start looking based on the design changes in Mongoid 5 and it's usage of the underlying driver...

When creating a `Mongo::Client`, the core driver spawns a monitor thread for each server that it discovers, which pings indefinitely to check the server status by default every 5 seconds. This client will never get garbage collected unless it is explicitly closed via `Mongo::Client#close`.

What it looks like is a new client keeps getting created - thus the server discovery runs again and adds the local server to the cluster. Each one of those log "Adding 127.0.0.1:27017 to the cluster" messages is basically where this happened. So we'll need to figure out why a new one is getting created.

Since the core driver is threadsafe, and Moped was not, we removed the "one client per thread" pattern in Mongoid in order to avoid this issue in standard multi-threaded cases, so I don't think that is the issue. My next thought is perhaps you are using `#with` often, ie `Model#with(...).some_method`... If you are using `#with` and changing options other than `collection`, `database`, `client`, `read` or `write` it would force a cluster topology change and would cause this... Is that potentially the case?

**Comment by lucasmartins** [comment]
Thanks a lot for the tips, with it I've been able to trace the problem to this code:
```ruby
# ... code that builds the calls_hashes Array
 
# THIS CODE SPAWNS NEW MONGO CONNECTIONS
unless Rails.env.production?
  line.calls.with(safe: true).create!(calls_hashes)
else
  line.calls.with(write: {w: 'majority'}, safe: true).create!(calls_hashes)
end
 
# ... code that schedules map&reduce jobs.
```

I changed it to `line.calls.create!(calls_hashes)` and the problem doesn't seem to happen anymore.

What is the recommended way for me to guarantee majority in the cluster for this operation?

**Comment by durran** [comment]
You should be doing:

```ruby
line.calls.with(write: { w: 'majority' }).create!(calls_hashes)
```

**Comment by lucasmartins** [comment]
Thanks!
