### ISSUE TITLE
.inc() updates model with incorrect value

### ISSUE THREAD

**Issue by veesahni** [mongoid/mongoid#4131]
Assume a model with a field x having value 1.  Now:

```ruby
instance1 = MyModel.find(id)
instance2 = MyModel.find(id)

instance1.inc(x: 1)
instance2.inc(x: 1)
```
At this point, since inc() is atomic, the actual value of x is 3, but ```instance2``` has a value of 2.  This causes a problem if there's code that assumes the updated attribute is correct.  

```ruby
# here, new_value doesn't contain the real server value of x
new_value = instance1.inc(x:1).x
```

The underlying issue is that the Mongoid implementation of inc() proactively updates the value of x without taking into consideration that the current value in the model may be stale:

```ruby
      def inc(increments)
        prepare_atomic_operation do |ops|
          process_atomic_operations(increments) do |field, value|
            increment = value.__to_inc__
            current = attributes[field]
            attributes[field] = (current || 0) + increment
            ops[atomic_attribute_name(field)] = increment
          end
          { "$inc" => ops }
        end
      end
    end
```

Either: 

1. the attribute should not get proactively updated with a possibly wrong value
2. the attribute should get updated with the correct value, perhaps using ```findAndModify``` with ```new: true```

**Comment by durran** [comment]
This works as designed. `#inc` uses `$inc` under the covers - if you want to do a `$findAndModify`, use `#find_and_modify`. We're not going to confuse users when calling `#inc` and executing another command.

There's also nothing we can do about this using $inc because:

1. Any document at any point in time in memory can be stale.
2. MongoDB has no transactions and we have no locking mehcanisms to prevent anything else from updating the document.
3. MongoDB does not return the updated document on normal update commands, so we don't know what the new value is.

**Comment by veesahni** [comment]
@durran I agree that calling it inc and using findAndModify under the hood would be odd.  That said, since we have no way of knowing what the new value is when using MongoDB $inc, perhaps it would make sense to not modify the attribute?

I think the current implementation could confuse a user into believing the updated attribute represents something provided by the server.
